MediaArea/MediaArea-Utils

buildrelease/Handle_OBS_results.py

Fix deb packages download (broken with new .debian tarballs)

---

preformaPackages/preformaPackages.sh

Add script to generate PREFORMA zip packages

---

MediaConch_SourceCode/BuildRelease.sh
MediaConch_SourceCode/PrepareSource.sh
MediaConch_SourceCode/UpgradeVersion.sh
MediaInfo/BuildRelease.sh
MediaInfo/PrepareSource.sh
MediaInfo/UpgradeVersion.sh
MediaInfoLib/BuildRelease.sh
MediaInfoLib/PrepareSource.sh
MediaInfoLib/UpgradeVersion.sh
build_release/Handle_OBS_results.py

Renaming mac scripts to avoid users confusion

---

build_release/Handle_OBS_results.py

x ARM bugfixe

---

build_release/Handle_OBS_results.py

Deactivation of the ARM distributions

---

MediaConch_SourceCode/BuildRelease.sh
MediaConch_SourceCode/PrepareSource.sh
MediaInfo/BuildRelease.sh
MediaInfo/PrepareSource.sh
MediaInfo/UpgradeVersion.sh
MediaInfoLib/PrepareSource.sh
MediaInfoLib/UpgradeVersion.sh
ZenLib/PrepareSource.sh
build_release/BuildRelease.sh
build_release/Handle_OBS_results.py
prepare_source/PrepareSource.sh
upgrade_version/UpgradeVersion.sh

+ MC : packaging the daemon for linux and PS.sh

---

MediaConch_SourceCode/BuildRelease.sh
MediaConch_SourceCode/PrepareSource.sh
MediaConch_SourceCode/UpgradeVersion.sh
build_release/BuildRelease.sh
build_release/Handle_OBS_results.py
prepare_source/PrepareSource.sh
upgrade_version/UpgradeVersion.sh

+ Create the directory for MC server

---

MediaConch_SourceCode/UpgradeVersion.sh
MediaInfo/UpgradeVersion.sh
MediaInfoLib/UpgradeVersion.sh
ZenLib/UpgradeVersion.sh

Support of MSVC2015 + MC-server

---

build_release/Handle_OBS_results.py

x Fix SQL request

---

build_release/Handle_OBS_results.py

x Protect tables names

---

MediaConch_SourceCode/UpgradeVersion.sh
MediaInfo/UpgradeVersion.sh
MediaInfoLib/UpgradeVersion.sh

x Reverse the automatic upgrade of MIL for the linux snapshots

---

MediaConch_SourceCode/BuildRelease.sh
MediaInfo/BuildRelease.sh
MediaInfoLib/BuildRelease.sh
ZenLib/BuildRelease.sh
build_release/Handle_OBS_results.py

Improvements on HOR.py

---

MediaConch_SourceCode/PrepareSource.sh
MediaInfo/PrepareSource.sh
MediaInfoLib/PrepareSource.sh
ZenLib/PrepareSource.sh
prepare_source/PrepareSource.sh
tarballs_preforma/Tarballs_preforma.sh
tarballs_preforma/tasks/Buildenv_debian.sh
tarballs_preforma/tasks/Buildenv_fedora.sh
tarballs_preforma/tasks/Buildenv_opensuse.sh
tarballs_preforma/tasks/Buildenv_ubuntu.sh
tarballs_preforma/tasks/Executables.sh
tarballs_preforma/tasks/Sources.sh

+ Use MediaConch-AllInOne for MC AllInclusive tarball

---

MediaConch_SourceCode/BuildRelease.sh
MediaInfo/BuildRelease.sh
MediaInfoLib/BuildRelease.sh
ZenLib/BuildRelease.sh

Rewriting of the error mails for Mac

---

tarballs_preforma/tasks/Buildenv_winmac.sh

Task Buildenv_winmac

---

tarballs_preforma/packages/Debian-8.txt
tarballs_preforma/packages/Ubuntu-14.04.txt
tarballs_preforma/packages/Ubuntu-15.10.txt
tarballs_preforma/tasks/Sources.sh

Complete source task

---

MediaInfo/UpgradeVersion.sh

Don’t upgrade MIL version for MI snapshots

---

tarballs_preforma/packages/Ubuntu-14.04.txt
tarballs_preforma/readmes/Readme_debian.txt
tarballs_preforma/readmes/Readme_fedora.txt
tarballs_preforma/readmes/Readme_opensuse.txt
tarballs_preforma/readmes/Readme_ubuntu.txt
tarballs_preforma/tasks/Buildenv_debian.sh
tarballs_preforma/tasks/Buildenv_ubuntu.sh

Add the Readme.txt + Debian task

---

tools/Readme.md
tools/file_to_bin.cpp

Signed-off-by: Florent Tribouilloy <florent@mediaarea.net>

Introduce utilities for MC

---

MediaConch_SourceCode/PrepareSource.sh

Update submodules when using AllInOne repository

---

CheckLinks/checkLinks.class.php
CheckLinks/checkMediaAreaLinks.php

Add chekLinks script

---

CheckLinks/checkLinks.class.php
CheckLinks/checkMediaAreaLinks.php

Handle links without http/https prefix

---

MediaInfoLib/PrepareSource.sh

Thanks to LoRd_MuldeR http://forum.doom9.org/showthread.php?p=1768340#post1768340

Do not remove zlib/contrib

---

build_release/Generate_DL_pages_dist.conf

Generate_DL_pages_dist.conf with sources

---

build_release/Handle_OBS_results.py
tarballs_preforma/tasks/Executables.sh

Handle Fedora 24 and Ubuntu 16.04

---

MediaConch_SourceCode/BuildRelease.sh
MediaConch_SourceCode/PrepareSource.sh
MediaConch_SourceCode/UpgradeVersion.sh
MediaInfo/BuildRelease.sh
MediaInfo/PrepareSource.sh
MediaInfo/UpgradeVersion.sh
MediaInfoLib/BuildRelease.sh
MediaInfoLib/PrepareSource.sh
MediaInfoLib/UpgradeVersion.sh
ZenLib/BuildRelease.sh
ZenLib/PrepareSource.sh
ZenLib/UpgradeVersion.sh
build_release/BuildRelease.sh
build_release/Generate_DL_pages.py
build_release/Handle_OBS_results.py
build_release/Handle_OBS_results_dist.conf
build_release/dl_templates/MC_arch_header
build_release/dl_templates/MI_arch_header

Add Arch Support in OBS shell scripts

---

build_release/Generate_DL_pages.py
build_release/Generate_DL_pages_dist.conf
build_release/dl_templates/MC_arch_header
build_release/dl_templates/MC_centos_header
build_release/dl_templates/MC_debian_header
build_release/dl_templates/MC_fedora_header
build_release/dl_templates/MC_linux_template
build_release/dl_templates/MC_linux_template_no_server
build_release/dl_templates/MC_mac_header
build_release/dl_templates/MC_opensuse_header
build_release/dl_templates/MC_rhel_header
build_release/dl_templates/MC_sle_header
build_release/dl_templates/MC_sources_header
build_release/dl_templates/MC_ubuntu_header
build_release/dl_templates/MC_windows_header
build_release/dl_templates/MC_windows_template

Update templates for MC download pages

---

MediaConch_SourceCode/PrepareSource.sh

This reverts commit 06013aaf20e1ae5c71bcffa73b10052b3b4a3fbf.

Revert "Solve incorrect version number in MC AllInclusive.7z package"

---

build_release/Generate_DL_pages.py
build_release/dl_templates/MI_linux_template
build_release/dl_templates/MI_sources_template

Update templates for MI download pages 

---

MediaConch_SourceCode/BuildRelease.sh
MediaConch_SourceCode/UpgradeVersion.sh
MediaInfo/BuildRelease.sh
MediaInfo/UpgradeVersion.sh
MediaInfoLib/BuildRelease.sh
MediaInfoLib/UpgradeVersion.sh
ZenLib/BuildRelease.sh
ZenLib/UpgradeVersion.sh
upgrade_version/UpgradeVersion.sh

Remove git -C usage

---

MediaConch_SourceCode/BuildRelease.sh
MediaConch_SourceCode/UpgradeVersion.sh
MediaInfo/BuildRelease.sh
MediaInfo/UpgradeVersion.sh
MediaInfoLib/BuildRelease.sh
MediaInfoLib/UpgradeVersion.sh
ZenLib/BuildRelease.sh
ZenLib/UpgradeVersion.sh
build_release/BuildRelease.sh
build_release/Handle_OBS_results.py
build_release/modules/deb.sh

Merge OBS repos

---

build_release/modules/deb.sh

Use environment to pass compressor options

---

build_release/modules/deb.sh

Correct tar options

---

build_release/Handle_OBS_results.py

Handle Debian 9/Ubuntu 15.10+ libs name

---

MediaConch_SourceCode/BuildRelease.sh
MediaInfo/BuildRelease.sh

Improve error reporting by mail for Windows

---

build_release/Handle_OBS_results.py

Download debug packages

---

MediaInfo/UpgradeVersion.sh

Increment CFBundleVersion in MediaInfo-Info.plist

---

MediaConch_SourceCode/BuildRelease.sh
MediaInfo/BuildRelease.sh
QCTools/BuildRelease.sh
QCTools/PrepareSource.sh
build_release/Handle_OBS_results.py

HOR.py for QCTools

---

build_release/Handle_OBS_results.py

Fix Ubuntu_Next target

---

QCTools/BuildRelease.sh
build_release/Handle_OBS_results.py

Static QCTools

---

AVIMetaEdit/BuildRelease.sh
BWFMetaEdit/BuildRelease.sh
DVAnalyzer/BuildRelease.sh
QCTools/BuildRelease.sh

Fix Windows binary signing

---

AVIMetaEdit/BuildRelease.sh
BWFMetaEdit/BuildRelease.sh
DVAnalyzer/BuildRelease.sh
QCTools/BuildRelease.sh

Fix signtool path

---

AVIMetaEdit/BuildRelease.sh
BWFMetaEdit/BuildRelease.sh
DVAnalyzer/BuildRelease.sh

Fix HOR.py invocation

---

QCTools/BuildRelease.sh
build_release/Generate_DL_pages.py
build_release/Generate_DL_pages_dist.conf
build_release/dl_templates/QC_arch_header
build_release/dl_templates/QC_centos_header
build_release/dl_templates/QC_debian_header
build_release/dl_templates/QC_fedora_header
build_release/dl_templates/QC_linux_template
build_release/dl_templates/QC_mac_header
build_release/dl_templates/QC_mac_template
build_release/dl_templates/QC_mageia_header
build_release/dl_templates/QC_opensuse_header
build_release/dl_templates/QC_rhel_header
build_release/dl_templates/QC_sle_header
build_release/dl_templates/QC_sources_header
build_release/dl_templates/QC_sources_template
build_release/dl_templates/QC_ubuntu_header
build_release/dl_templates/QC_windows_header
build_release/dl_templates/QC_windows_template

Add QCTools to Generate_DL_pages.py

---

build_release/BuildRelease.sh

Don't make snapshot if the repo was unmodified

---

build_release/Generate_DL_pages_dist.conf
build_release/Handle_OBS_results.py
build_release/modules/deb.sh

Add Debian Next

---

AVIMetaEdit/BuildRelease.sh
BWFMetaEdit/BuildRelease.sh
DVAnalyzer/BuildRelease.sh
MediaConch_SourceCode/BuildRelease.sh
MediaInfo/BuildRelease.sh
MediaInfoLib/BuildRelease.sh
QCTools/BuildRelease.sh
ZenLib/BuildRelease.sh
build_release/BuildRelease.sh
build_release/Handle_OBS_results.py

Rebuild snapshot on same directory if no code change

---

QCTools/BuildRelease.sh

Add QCtools DebugInfo for MSVC package

---

MediaConch_SourceCode/UpgradeVersion.sh
build_release/BuildRelease.sh

Add file to MC UV.sh

---

MediaConch_SourceCode/BuildRelease.sh
MediaConch_SourceCode/UpgradeVersion.sh
MediaInfo/BuildRelease.sh
MediaInfo/UpgradeVersion.sh
build_release/BuildRelease.sh
build_release/Config_dist.sh

Signed-off-by: Maxime Gervais gervais.maxime@gmail.com

Automate MediaConch Snap and AppImage

---

build_release/Handle_OBS_results.py
build_release/Handle_OBS_results_dist.conf
build_release/Repo.py
build_release/Repo_dist.conf

Add deb and rpm repositories support

---

MediaConch_SourceCode/BuildRelease.sh
MediaInfo/BuildRelease.sh
build_release/BuildRelease.sh

Add --only-images option to BR.sh

---

MediaConch_SourceCode/BuildRelease.sh
MediaInfo/BuildRelease.sh

Fix images build

---

DVAnalyzer/BuildRelease.sh
MediaConch_SourceCode/PrepareSource.sh
MediaInfoLib/PrepareSource.sh
QCTools/BuildRelease.sh
QCTools/PrepareSource.sh
build_release/Generate_DL_pages.py
build_release/modules/win.sh
prepare_source/PrepareSource.sh
tarballs_preforma/tasks/Buildenv_win.sh

Add external dependencies to MediaConch packages

---

build_release/Generate_DL_pages.py
build_release/Repo.py
build_release/Repo_dist.conf

Repo.py: add package from cmdline

---

MediaConch_SourceCode/BuildRelease.sh
MediaInfo/BuildRelease.sh

Fix windows packages

---

build_release/Repo.py
build_release/Repo_dist.conf
build_release/repo_templates/deb_control_template
build_release/repo_templates/rpm_spec_template

+ activation packages version number
+ add activation packages to repositories
+ fix RHEL/CentOS5
+ generic activations packages for all supported distributions

Repo.py update

---

MediaConch_SourceCode/BuildRelease.sh

Fix MC build report by mail

---

AVIMetaEdit/BuildRelease.sh
BWFMetaEdit/BuildRelease.sh
DVAnalyzer/BuildRelease.sh
QCTools/BuildRelease.sh
build_release/Config_dist.sh
build_release/repo_templates/deb_postinst_template

Remove hardcoded path + fix repo deb

---

build_release/Repo.py

Repo: fix cleaning of old packages

---

build_release/Diff/zlib_MT.diff
build_release/Diff/zlib_XP.diff

Update after https://github.com/MediaArea/zlib updated

---

MediaConch_SourceCode/UpgradeVersion.sh
MediaInfo/UpgradeVersion.sh

Fix ZenLib version update

---

AVIMetaEdit/UpgradeVersion.sh
BWFMetaEdit/UpgradeVersion.sh
DVAnalyzer/UpgradeVersion.sh

Fix UV.sh for some projects

---

build_release/dl_templates/MI_windows_template

Fix MediaInfo Windows download page template

---

QCTools/BuildRelease.sh
QCTools/UpgradeVersion.sh

QCTools: update version in Source/Core/Core.cpp

---

QCTools/PrepareSource.sh
build_release/BuildRelease.bat

forgotten timeouts

---

build_release/dl_templates/MC_appimage_template
build_release/dl_templates/MI_appimage_template
build_release/dl_templates/QC_appimage_template

New AppImage filenames

---

build_release/Handle_OBS_results.py

Fix -doc exclude list

---

build_release/Generate_DL_pages.py
build_release/Generate_DL_pages_dist.conf
build_release/dl_templates/MC_mac_template
build_release/dl_templates/QC_mac_template

dlpages: add macstore link for MediaConch and QCTools

---

build_release/BuildRelease.bat

BuildRelease.bat update

---

build_release/Generate_DL_pages.py

dlpages: fix command for deb packages

---

build_release/Repo_dist.conf
prepare_source/modules/deb.sh

OBS: Add Debian 9

---

build_release/Generate_DL_pages_dist.conf
build_release/Handle_OBS_results.py

Fix debian 9

---

MOVMetaEdit/BuildRelease.sh
MOVMetaEdit/PrepareSource.sh
MOVMetaEdit/UpgradeVersion.sh
build_release/Handle_OBS_results_dist.conf
modules/project.sh

New Project: MOVMetaEdit

---

ZenLib/UpgradeVersion.sh

ZenLib: update version number in CMake project

---

build_release/Diff/MediaInfoLib_MP.diff
build_release/Diff/MediaInfoLib_MT.diff

Update diff files

---

MOVMetaEdit/PrepareSource.sh

Update MOVMetaEdit PS.sh

---

MOVMetaEdit/PrepareSource.sh

Try to fix MOVMetaEdit Windows build

---

MOVMetaEdit/PrepareSource.sh
MOVMetaEdit/UpgradeVersion.sh

Update MOVMetaEdit script for splitted debian packages

---

DVAnalyzer/PrepareSource.sh
DVAnalyzer/UpgradeVersion.sh

Update DVAnalyzer script for splitted debian packages

---

AVIMetaEdit/BuildRelease.sh
AVIMetaEdit/PrepareSource.sh
AVIMetaEdit/UpgradeVersion.sh

Update scripts for AVIMetaEdit

---

QCTools/PrepareSource.sh
QCTools/UpgradeVersion.sh

QCTools: splitted deb package for Qt4/Qt5

---

ZenLib/UpgradeVersion.sh

ZenLib CMake version

---

build_release/Generate_DL_pages.py
build_release/dl_templates/MI_repo_header
build_release/dl_templates/MI_repo_template

Update repository template

---

AVIMetaEdit/BuildRelease.sh
AVIMetaEdit/PrepareSource.sh
BWFMetaEdit/BuildRelease.sh
BWFMetaEdit/PrepareSource.sh
DVAnalyzer/BuildRelease.sh
DVAnalyzer/PrepareSource.sh
MOVMetaEdit/BuildRelease.sh
MOVMetaEdit/PrepareSource.sh
modules/project.sh

Remove underscores

---

build_release/dl_templates/AM_windows_template
build_release/dl_templates/BM_windows_template

Fix dlpages

---

build_release/BuildRelease.bat

Update bcb path

---

MediaInfo/UpgradeVersion.sh
MediaInfoLib/UpgradeVersion.sh

Update MI and MIL UV.sh

---

MediaConch_SourceCode/UpgradeVersion.sh
build_release/BuildRelease.bat
build_release/Diff/MediaConch_MD.diff
build_release/Diff/MediaConch_MT.diff
build_release/Diff/MediaInfoLib_MP.diff
build_release/Diff/MediaInfoLib_MT.diff
build_release/Diff/MediaInfoLib_XP.diff
build_release/Diff/MediaInfo_MT.diff
build_release/Diff/MediaInfo_NoGUI.diff
build_release/Diff/MediaInfo_XP.diff
build_release/Diff/ZenLib_MT.diff
build_release/Diff/ZenLib_XP.diff
build_release/Diff/jansson_MT.diff
build_release/Diff/libevent_MT.diff
build_release/Diff/libxml2_MT.diff
build_release/Diff/libxslt_MT.diff
build_release/Diff/zlib_MT.diff
build_release/Diff/zlib_XP.diff

Use MSVC2017 for build

---

build_release/Generate_DL_pages_dist.conf

SLE 12 SP3

---

MediaInfo/UpgradeVersion.sh
MediaInfoLib/UpgradeVersion.sh

Fix MI and MIL UpgradeVersion.sh

---

build_release/Handle_OBS_results.py

Generate script for delayed export to repositories

---

AVIMetaEdit/UpgradeVersion.sh
BWFMetaEdit/UpgradeVersion.sh
DVAnalyzer/UpgradeVersion.sh

Missing files un UV.sh

---

build_release/Generate_DL_pages_dist.conf

Fedora 27/Linux Mint 18.3

---

build_release/Repo.py

Re-fix Repo.py

---

RAWCooked/BuildRelease.sh
RAWCooked/PrepareSource.sh
RAWCooked/UpgradeVersion.sh
build_release/Handle_OBS_results_dist.conf
modules/project.sh

rawcooked files

---

RAWcooked/BuildRelease.sh
RAWcooked/PrepareSource.sh
RAWcooked/UpgradeVersion.sh
build_release/Handle_OBS_results_dist.conf
modules/project.sh

RAWCooked -> RAWcooked

---

build_release/dl_templates/DA_mac_template
build_release/dl_templates/DA_windows_template

Fix DV Analyzer templates

---

build_release/Repo_dist.conf

Fix ubuntu list

---

build_release/Generate_DL_pages_dist.conf

Add fedora 28

---

build_release/Generate_DL_pages.py
prepare_source/modules/deb.sh

Remove some old distributions

---

RAWcooked/UpgradeVersion.sh

Update version in Source/Lib/RAWcooked/RAWcooked.cpp

---

RAWcooked/UpgradeVersion.sh

Update version in Source/CLI/rawcooked.1

---

tools/mk_xml_to_cpp.cpp

Update matroska elements definitions from xml

---

MediaConch_SourceCode/PrepareSource.sh

Update libxml2/libxslt repositories url

---

DVAnalyzer/UpgradeVersion.sh
MediaConch_SourceCode/UpgradeVersion.sh
MediaInfo/UpgradeVersion.sh
MediaInfoLib/UpgradeVersion.sh
ZenLib/UpgradeVersion.sh
build_release/Handle_OBS_results.py

Handle packages with suffix for RHEL/CentOS

---

build_release/Generate_DL_pages_dist.conf

Add OpenSUSE Leap 15.0

---

build_release/Generate_DL_pages.py
build_release/Generate_DL_pages_dist.conf
build_release/dl_templates/QC_rhel_header

QCtools: link to CentOS packages for RHEL

---

build_release/BuildRelease.bat
build_release/dl_templates/MC_windows_template
build_release/dl_templates/MI_windows_template

MediaInfoLib: Handle Windows zip archive

---

CheckLinks/checkMediaAreaLinks.php
RAWcooked/PrepareSource.sh
RAWcooked/UpgradeVersion.sh

Update scripts for RAWcooked

---

MediaInfo/UpgradeVersion.sh

Update versions in MediaInfo Android GUI

---

MOVMetaEdit/UpgradeVersion.sh

MOVMetaEdit config.h file has moved

---

MediaInfo/UpgradeVersion.sh

Fix version number in MI AppxManifest.xml

---

build_release/Diff/RAWcooked_MT.diff

Static runtime patch for RAWcooked

---

build_release/Diff/RAWcooked_MT.diff

Fix RAWcooked_MT.diff

---

MediaInfo/UpgradeVersion.sh

Version upgrade for MI UWP GUI

---

MediaInfo/UpgradeVersion.sh
MediaInfoLib/UpgradeVersion.sh
RAWcooked/UpgradeVersion.sh

Update version in MSVC2019 project files

---

build_release/Diff/RAWcooked_MT.diff

Update RAWcooked static patch

---

MediaConch_SourceCode/UpgradeVersion.sh

MediaConch UV.sh: Add Info.plist for direct distribution

---

build_release/Diff/RAWcooked_MT.diff
build_release/Generate_DL_pages.py
build_release/Generate_DL_pages_dist.conf
build_release/Handle_OBS_results.py
build_release/Repo.py
build_release/Repo_dist.conf
build_release/dl_templates/AM_raspbian_header
build_release/dl_templates/BM_raspbian_header
build_release/dl_templates/DA_raspbian_header
build_release/dl_templates/MC_raspbian_header
build_release/dl_templates/MI_raspbian_header
build_release/dl_templates/MM_raspbian_header
build_release/dl_templates/QC_raspbian_header
build_release/dl_templates/RC_raspbian_header
build_release/repo_templates/deb_postinst_template
prepare_source/modules/deb.sh

+ RAWcooked static patch update

 Raspbian support 

---

MediaInfoLib/UpgradeVersion.sh

Update version for MIL Android sample project

---

build_release/Generate_DL_pages_dist.conf
build_release/Handle_OBS_results.py
build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add distributions

---

MediaInfo/UpgradeVersion.sh
upgrade_version/UpgradeVersion.sh

Add --date option to UV.sh and update appdata xml

---

build_release/Repo.py

Fix repository package for debian 10

---

build_release/Generate_DL_pages_dist.conf
build_release/Repo.py
build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add Raspbian 10

---

build_release/Repo.py
build_release/Repo_dist.conf

Syntax errors

---

build_release/dl_templates/AM_mac_template
build_release/dl_templates/BM_mac_template
build_release/dl_templates/DA_mac_template
build_release/dl_templates/MC_mac_template
build_release/dl_templates/MI_mac_template
build_release/dl_templates/MM_mac_template
build_release/dl_templates/QC_mac_template

Use geo.itunes.apple.com instead of itunes.apple.com

---

build_release/Handle_OBS_results_dist.conf
dvrescue/PrepareSource.sh
dvrescue/UpgradeVersion.sh
modules/project.sh

Add project files for dvrescue

---

build_release/Generate_DL_pages_dist.conf
build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add Ubuntu 19.10 and Fedora 31

---

dvrescue/UpgradeVersion.sh

Fix DVRescue UV.sh

---

dvrescue/UpgradeVersion.sh

Update path for DVRescue.rc in UV.sh

---

QCTools/PrepareSource.sh

Update ffmpeg git url in QCtools PS.sh

---

QCTools/UpgradeVersion.sh

Update QCTools UV.sh

---

QCTools/PrepareSource.sh

Update QCTools dependancies

---

RAWcooked/UpgradeVersion.sh

Update RAWcooked UV.sh

---

QCTools/UpgradeVersion.sh

QCTools: Fix version string

---

build_release/Generate_DL_pages_dist.conf
build_release/Repo.py
build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add Ubuntu 20.04 (with arm support) and Fedora 32

---

MediaInfo/UpgradeVersion.sh
prepare_source/modules/deb.sh

Add deb10 target

---

build_release/BuildRelease.bat

Update signtool.exe command line

---

build_release/Repo.py

Fix cleaning of arm repositories

---

BWFMetaEdit/UpgradeVersion.sh

Update BWFMetaEdit appdata xml

---

build_release/Handle_OBS_results.py
build_release/Handle_OBS_results_dist.conf
build_release/dl_templates/AM_arch_header
build_release/dl_templates/BM_arch_header
build_release/dl_templates/DA_arch_header
build_release/dl_templates/MC_arch_header
build_release/dl_templates/MI_arch_header
build_release/dl_templates/MM_arch_header
build_release/dl_templates/QC_arch_header

Update to new arch Linux package format

---

QCTools/PrepareSource.sh

QCtools PS.sh: switch to forked qwt 6.1.5

---

QCTools/PrepareSource.sh

QCtools PS.sh: Use master branch for qwt

---

RAWcooked/UpgradeVersion.sh

RAWcooked UV.sh: Update RAWcooked.cpp path

---

build_release/Generate_DL_pages_dist.conf
build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add Ubuntu 20.10 and Fedora 33

---

build_release/Handle_OBS_results_dist.conf

Add ffmpeg-ma project

---

build_release/Handle_OBS_results_dist.conf
dvrescue/PrepareSource.sh

dvrescue: Add GUI

---

dvrescue/UpgradeVersion.sh

dvrescue: Add installer tot UV.sh

---

dvrescue/PrepareSource.sh

dvrescue: add ffmpeg

---

MediaConch_SourceCode/PrepareSource.sh

Generate MediaConch Library FromSource archives

---

build_release/repo_templates/rpm_spec_template

fix https://sourceforge.net/p/mediainfo/feature-requests/551/.

Use centOS repository link for OracleLinux

---

dvrescue/UpgradeVersion.sh

Fix dvrescue CLI on older linux distributions

---

build_release/BuildRelease.bat
build_release/Diff/MediaInfoLib_MP.diff
build_release/Diff/MediaInfoLib_MT.diff
build_release/Diff/MediaInfo_MT.diff
build_release/Diff/MediaInfo_NoGUI.diff
build_release/Diff/ZenLib_MT.diff

Update to MSVC2019

---

dvrescue/PrepareSource.sh

dvrescue: Use ffmpeg 4.4 for builds

---

BWFMetaEdit/UpgradeVersion.sh

Fix BWFMetaEdit UV.sh

---

build_release/repo_templates/rpm_spec_template

Fix repo activation package for openSUSE

---

build_release/repo_templates/rpm_spec_template

Fix repo activation package for openSUSE fix

---

dvrescue/PrepareSource.sh

Update dvrescue's qwt to 6.2.0

---

build_release/Generate_DL_pages_dist.conf
build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add Ubuntu 21.04 and Fedora 34

---

tools/irt_xml.py

Get files from xml

---

MediaConch_SourceCode/UpgradeVersion.sh
build_release/Diff/MediaConch_MD.diff
build_release/Diff/MediaConch_MT.diff
build_release/Diff/jansson_MT.diff
build_release/Diff/libevent_MT.diff
build_release/Diff/libxml2_MT.diff
build_release/Diff/libxslt_MT.diff
build_release/Diff/zlib_MT.diff

Update MC patches to VS2019

---

build_release/Generate_DL_pages_dist.conf
build_release/Handle_OBS_results.py
build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add Debian 11

---

build_release/Generate_DL_pages_dist.conf
build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add Fedora 35, Ubuntu 21.10 and Mageia 8

---

CheckLinks/checkLinks.class.php
CheckLinks/checkMediaAreaLinks.php

Update CheckLinks script

---

dvrescue/PrepareSource.sh

Add more dvrescue dependencies

---

build_release/Handle_OBS_results_dist.conf
modules/project.sh
sony9pin/PrepareSource.sh
sony9pin/UpgradeVersion.sh

Add sony9pin project

---

QCTools/PrepareSource.sh

Use ffmpeg 4.4.1 for QCTools

---

build_release/Generate_DL_pages_dist.conf
build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add Raspbian 11

---

build_release/Diff/MediaInfoLib_MT.diff

Update MediaInfoLib patches

---

build_release/Generate_DL_pages_dist.conf
build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add Ubuntu 22.04 and Fedora 36

---

RAWcooked/PrepareSource.sh

Rawcooked: Add version number in obs sources

---

dvrescue/PrepareSource.sh

Use FFmpeg git for dvrescue

---

dvrescue/UpgradeVersion.sh

UpgradeVersion for dvrescue deb11 files

---

ZenLib/UpgradeVersion.sh

Fix ZenLib UV.sh

---

build_release/handleOBSResults/conf/dist.conf
build_release/handleOBSResults/handleOBSResults.py
build_release/handleOBSResults/plugins/base.py
build_release/handleOBSResults/plugins/db.py
build_release/handleOBSResults/plugins/filelogger.py
build_release/handleOBSResults/plugins/repo.py
build_release/handleOBSResults/plugins/versioned.py

handleOBSResult python3 rework

---

build_release/handleOBSResults/handleOBSResults.py

hor: fix invalid remote filename

---

dvrescue/PrepareSource.sh

dvrescue: add freetype to package

---

build_release/handleOBSResults/handleOBSResults.py

hor: Fix error when an arch is listed but missing on obs

---

build_release/Diff/RAWcooked_MT.diff

Apply RAWcooked patches to the right project

---

build_release/Repo.py

Deb repository: Remove duplicate freight-cache call

---

build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add Debian/Raspbian 12

---

build_release/repo_templates/rpm_spec_template

Also try to catch others RHEL clones

Add AlmaLinux as link to RockyLinux in repo template

---

MediaInfo/UpgradeVersion.sh
MediaInfoLib/UpgradeVersion.sh

MI & MIL: write full version in nsis script

---

QCTools/PrepareSource.sh

QTAVPlayer fails to build with current development branch

Pin to ffmpeg 6.1 for QCTools

---

build_release/BuildRelease.bat

This reverts commit 7cdedc5fd40c652c84b13774b8cacceb914cc256.

Revert "Update bcc path"

---

build_release/Repo.py

Fixes MediaArea/MediaInfo#1061

Fix cleaning of old deb packages

---

build_release/Generate_DL_pages_dist.conf
build_release/Repo_dist.conf
prepare_source/modules/deb.sh

Add Ubuntu 25.04 and Fedora 42
